# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 151a3e972d3f73f0a238b1e7af35e779e1fe9850ce86bba3cc0fe75f382c7fb2020967c64a3715953a35d07ff697d648921bc22623975dc95e43e07c732768da

test:
  secret_key_base: 01be09396357d629666a68e2a5f6dce2ce6d0dd474ae75195b63a876f27661b71e743e22021202f63eab6a90e4b1ad31f73fc916ed7b551d7ae534e4767c1963

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
